// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Alert': typeof import("../components/Alert.vue")['default'],
    'Anchor': typeof import("../components/Anchor.vue")['default'],
    'Button': typeof import("../components/Button.vue")['default'],
    'Error': typeof import("../components/Error.vue")['default'],
    'SkeletonCard': typeof import("../components/SkeletonCard.vue")['default'],
    'ActionSheetBody': typeof import("../components/ActionSheet/Body.vue")['default'],
    'ActionSheetHeader': typeof import("../components/ActionSheet/Header.vue")['default'],
    'ActionSheetOverlay': typeof import("../components/ActionSheet/Overlay.vue")['default'],
    'ActionSheet': typeof import("../components/ActionSheet/index.vue")['default'],
    'AppFooter': typeof import("../components/App/AppFooter.vue")['default'],
    'AppNav': typeof import("../components/App/AppNav.vue")['default'],
    'BuilderNavbar': typeof import("../components/Builder/Navbar.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtImg': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.vue")['default'],
    'NuxtPicture': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture.vue")['default']
    'LazyAlert': typeof import("../components/Alert.vue")['default'],
    'LazyAnchor': typeof import("../components/Anchor.vue")['default'],
    'LazyButton': typeof import("../components/Button.vue")['default'],
    'LazyError': typeof import("../components/Error.vue")['default'],
    'LazySkeletonCard': typeof import("../components/SkeletonCard.vue")['default'],
    'LazyActionSheetBody': typeof import("../components/ActionSheet/Body.vue")['default'],
    'LazyActionSheetHeader': typeof import("../components/ActionSheet/Header.vue")['default'],
    'LazyActionSheetOverlay': typeof import("../components/ActionSheet/Overlay.vue")['default'],
    'LazyActionSheet': typeof import("../components/ActionSheet/index.vue")['default'],
    'LazyAppFooter': typeof import("../components/App/AppFooter.vue")['default'],
    'LazyAppNav': typeof import("../components/App/AppNav.vue")['default'],
    'LazyBuilderNavbar': typeof import("../components/Builder/Navbar.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.vue")['default'],
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture.vue")['default']
  }
}
export const Alert: typeof import("../components/Alert.vue")['default']
export const Anchor: typeof import("../components/Anchor.vue")['default']
export const Button: typeof import("../components/Button.vue")['default']
export const Error: typeof import("../components/Error.vue")['default']
export const SkeletonCard: typeof import("../components/SkeletonCard.vue")['default']
export const ActionSheetBody: typeof import("../components/ActionSheet/Body.vue")['default']
export const ActionSheetHeader: typeof import("../components/ActionSheet/Header.vue")['default']
export const ActionSheetOverlay: typeof import("../components/ActionSheet/Overlay.vue")['default']
export const ActionSheet: typeof import("../components/ActionSheet/index.vue")['default']
export const AppFooter: typeof import("../components/App/AppFooter.vue")['default']
export const AppNav: typeof import("../components/App/AppNav.vue")['default']
export const BuilderNavbar: typeof import("../components/Builder/Navbar.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture.vue")['default']
export const LazyAlert: typeof import("../components/Alert.vue")['default']
export const LazyAnchor: typeof import("../components/Anchor.vue")['default']
export const LazyButton: typeof import("../components/Button.vue")['default']
export const LazyError: typeof import("../components/Error.vue")['default']
export const LazySkeletonCard: typeof import("../components/SkeletonCard.vue")['default']
export const LazyActionSheetBody: typeof import("../components/ActionSheet/Body.vue")['default']
export const LazyActionSheetHeader: typeof import("../components/ActionSheet/Header.vue")['default']
export const LazyActionSheetOverlay: typeof import("../components/ActionSheet/Overlay.vue")['default']
export const LazyActionSheet: typeof import("../components/ActionSheet/index.vue")['default']
export const LazyAppFooter: typeof import("../components/App/AppFooter.vue")['default']
export const LazyAppNav: typeof import("../components/App/AppNav.vue")['default']
export const LazyBuilderNavbar: typeof import("../components/Builder/Navbar.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture.vue")['default']
export const componentNames: string[]
